kind: pipeline
name: react-ci-cd

steps:
  - name: build
    image: node:8.16.1-alpine
    commands:
      - npm install 

  - name: test
    commands:
      - npm test
      - npm run build

  - name: notify
    image: plugins/slack
    settings:
      webhook: 
        from_secret: slack
      channel: drone-zakaria