kind: pipeline
name: react-ci-cd

steps:
  - name: build
    image: node:8.16.1-alpine
    commands:
      - npm install 
      - npm run build
  - name: test
    image: node:8.16.1-alpine
    commands:
      - npm test
      
  - name: notify
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack
      channel: drone-zakaria
